# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://ak

trigger:
- main

pool:
  name: 'JamesBond'

variables:
  terraformVersion: '1.6.6'
  terraformPath: 'C:\Users\buildagent\terraform' # change buildagent to your agent service user

steps:
- powershell: |
    Write-Host "Installing Terraform..."
    New-Item -ItemType Directory -Path "$(terraformPath)" -Force | Out-Null
    $url = "https://releases.hashicorp.com/terraform/$(terraformVersion)/terraform_$(terraformVersion)_windows_amd64.zip"
    Invoke-WebRequest -Uri $url -OutFile "terraform.zip"
    Expand-Archive terraform.zip -DestinationPath "$(terraformPath)" -Force
    & "$(terraformPath)\terraform.exe" -version
  displayName: 'Install Terraform on Windows'

- powershell: |
    Write-Host "Running Terraform..."
    & "$(terraformPath)\terraform.exe" init
    & "$(terraformPath)\terraform.exe" plan -out=tfplan
    & "$(terraformPath)\terraform.exe" apply -auto-approve tfplan
  displayName: 'Terraform Apply'
