# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://ak

trigger:
- main

pool:
  name: 'JamesBond'

steps:
- powershell: |
    Write-Host "Installing Terraform..."
    $terraformVersion = "1.6.6"
    Invoke-WebRequest -Uri "https://releases.hashicorp.com/terraform/$terraformVersion/terraform_${terraformVersion}_windows_amd64.zip" -OutFile "terraform.zip"
    Expand-Archive terraform.zip -DestinationPath "$env:C:\Users\terraform" -Force
    $env:Path += ";$env:USERPROFILE\terraform"
    terraform -version
  displayName: 'Install Terraform on Windows'

- powershell: |
    Write-Host "Running Terraform..."
    terraform init
    terraform plan -out=tfplan
    terraform apply -auto-approve tfplan
  displayName: 'Terraform Apply'
